#!/bin/python
import struct
with open("example.cimg", "wb") as f:
    f.write(b"cIMG")                     # magic
    f.write((1).to_bytes(4, "little"))   # version
    f.write((79).to_bytes(2, "little"))  # width
    f.write((24).to_bytes(4, "little"))  # height

    # pixel data (all spaces = valid ASCII 0x20)
    f.write(b"\x20" * (79 * 24))
